version: '3'

services:
  #Banco de Dados Postgres
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gobarber
    ports:
      - '5433:5432'
    volumes:
      - postgres:/data/postgres

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

volumes:
  postgres:
  mongodb:
